# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 420)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calcular.setGeometry(QtCore.QRect(340, 310, 121, 41))
        self.pushButton_calcular.setObjectName("pushButton_calcular")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 20, 181, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_ancho = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_ancho.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_ancho.setObjectName("lineEdit_ancho")
        self.gridLayout.addWidget(self.lineEdit_ancho, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_costo = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_costo.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_costo.setObjectName("lineEdit_costo")
        self.gridLayout.addWidget(self.lineEdit_costo, 1, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(40, 180, 161, 71))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.formLayout = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout.setObjectName("formLayout")
        self.label_a = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_a.setFont(font)
        self.label_a.setScaledContents(False)
        self.label_a.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a.setWordWrap(True)
        self.label_a.setObjectName("label_a")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_a)
        self.lineEdit_a = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_a.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_a)
        self.label_b = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_b.setFont(font)
        self.label_b.setScaledContents(False)
        self.label_b.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b.setWordWrap(True)
        self.label_b.setObjectName("label_b")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_b)
        self.lineEdit_b = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_b.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_b.setObjectName("lineEdit_b")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_b)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 20, 281, 261))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("GUI/Dimensiones.PNG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 160, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 330, 281, 36))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_resultados = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_resultados.setFont(font)
        self.label_resultados.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_resultados.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_resultados.setScaledContents(False)
        self.label_resultados.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_resultados.setWordWrap(True)
        self.label_resultados.setObjectName("label_resultados")
        self.horizontalLayout.addWidget(self.label_resultados)
        self.label_totalPiezas = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_totalPiezas.setFont(font)
        self.label_totalPiezas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_totalPiezas.setText("")
        self.label_totalPiezas.setObjectName("label_totalPiezas")
        self.horizontalLayout.addWidget(self.label_totalPiezas)
        self.label_resultados_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_resultados_2.setFont(font)
        self.label_resultados_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_resultados_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_resultados_2.setScaledContents(False)
        self.label_resultados_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_resultados_2.setWordWrap(True)
        self.label_resultados_2.setObjectName("label_resultados_2")
        self.horizontalLayout.addWidget(self.label_resultados_2)
        self.label_totalMetros = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_totalMetros.setFont(font)
        self.label_totalMetros.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_totalMetros.setText("")
        self.label_totalMetros.setObjectName("label_totalMetros")
        self.horizontalLayout.addWidget(self.label_totalMetros)
        self.label_resultados_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_resultados_3.setFont(font)
        self.label_resultados_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_resultados_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_resultados_3.setScaledContents(False)
        self.label_resultados_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_resultados_3.setWordWrap(True)
        self.label_resultados_3.setObjectName("label_resultados_3")
        self.horizontalLayout.addWidget(self.label_resultados_3)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(20, 260, 191, 61))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_piezasXmetro = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_piezasXmetro.setFont(font)
        self.label_piezasXmetro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_piezasXmetro.setText("")
        self.label_piezasXmetro.setObjectName("label_piezasXmetro")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_piezasXmetro)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_costoPieza = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_costoPieza.setFont(font)
        self.label_costoPieza.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_costoPieza.setText("")
        self.label_costoPieza.setObjectName("label_costoPieza")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_costoPieza)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 559, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_calcular.setText(_translate("MainWindow", "CALCULAR"))
        self.label_2.setText(_translate("MainWindow", "Ancho Tela [ cm ] "))
        self.label_4.setText(_translate("MainWindow", "$ Costo tela / metro"))
        self.label_a.setText(_translate("MainWindow", "a [cm] ="))
        self.label_b.setText(_translate("MainWindow", "b [cm] ="))
        self.label_3.setText(_translate("MainWindow", "DIMENSIONES DE LA PIEZA:"))
        self.label_resultados.setText(_translate("MainWindow", "Salen :"))
        self.label_resultados_2.setText(_translate("MainWindow", "piezas en "))
        self.label_resultados_3.setText(_translate("MainWindow", "metros "))
        self.label_5.setText(_translate("MainWindow", "#Piezas en 1 metro:"))
        self.label_7.setText(_translate("MainWindow", "$ Costo/ pieza : "))
